version: "3.8"

services:
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: ["redis-server", "--appendonly", "yes"]

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: userService
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d  # 👈 This runs scripts at container first boot

  user-service:
    build:
      context: ./UserService
    container_name: user-service
    ports:
      - "8081:8081"
    environment:
      - SERVER_PORT=8081
      - SEARCH_SERVICE_URL=http://search-service:8082
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/userService
      - MERCHANT_SERVICE_URL=http://merchant-service:8084
      - USER_SERVICE_URL=http://user-service:8081
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=1234
      - REDIS_HOST=redis
    depends_on:
      - redis
      - rabbitmq
      - postgres

  search-service:
    build:
      context: ./SearchService
    container_name: search-service
    ports:
      - "8082:8082"
    environment:
      - SERVER_PORT=8082
      - REDIS_HOST=redis
      - RABBITMQ_HOST=rabbitmq
      - MERCHANT_SERVICE_URL=http://merchant-service:8084
      - USER_SERVICE_URL=http://user-service:8081

    depends_on:
      - redis
      - rabbitmq

  merchant-service:
    build:
      context: ./merchant-service
    container_name: merchant-service
    ports:
      - "8084:8084"
    environment:
      - SERVER_PORT=8084
      - REDIS_HOST=redis
      - RABBITMQ_HOST=rabbitmq
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/merchant_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=1234
    depends_on:
      - postgres
      - rabbitmq

volumes:
  redis-data:
  rabbitmq-data:
  postgres-data:
