version: '3.8'

services:

  postgres:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_DB: transactions
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - transaction-network

  transaction_app:
    build: .
    container_name: transaction_app
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_APPLICATION_NAME: Transaction
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/transactions
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver

      # JPA & Hibernate
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.PostgreSQLDialect
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_GENERATE_DDL: "true"
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL: "true"
      SPRING_JPA_PROPERTIES_HIBERNATE_USE_SQL_COMMENTS: "true"
      SPRING_MAIL_HOST: smtp.gmail.com
      SPRING_MAIL_PORT: 587

      SPRING_MAIL_USERNAME: eslam4gamal111@gmail.com

      SPRING_MAIL_PASSWORD: zeut prjm asyx pmnq

      SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH: "true"
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE: "true"
    networks:
      - transaction-network

volumes:
  postgres_data:

networks:
  transaction-network:
