apiVersion: v1
kind: Service
metadata:
  name: api-gateway-service
spec:
  type: NodePort
  selector:
    app: api-gateway-service
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30050
